apps/product/urls.py
from django.urls import path

from apps.product.views import (
    ProductCreateView,
    ProductListView,
    ProductDetailView,
    ProductUpdateView,
    ProductDeleteView,
)

urlpatterns = [
    path('', ProductListView.as_view(), name='product-list'),
    path('create', ProductCreateView.as_view(), name='product-create'),
    path('<uuid:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('update/<uuid:pk>/', ProductUpdateView.as_view(), name='product-update'),
    path('delete/<uuid:pk>/', ProductDeleteView.as_view(), name='product-delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("apps.product.urls", 'product'), namespace='product'))
]

apps/product/models.py
import uuid as uuid_lib

from django.db import models


class Product(models.Model):
    class Meta:
        ordering = ["-created"]

    name = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    uuid = models.UUIDField(primary_key=True, default=uuid_lib.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    logo = models.URLField(blank=True, null=True)
    rotate_duration = models.FloatField(null=True)
    modified = models.BooleanField(default=False)

    def __str__(self):
        return self.name

apps/product/forms.py
from django import forms

from apps.product.models import Product
from config.validators import validate_file_size, validate_file_type


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description"]

    logo_file = forms.FileField(required=True, validators=[validate_file_size, validate_file_type])

apps/product/views.py
import logging

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
)
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DeleteView, DetailView

from apps.product.forms import ProductForm
from apps.product.models import Product
from apps.product.tasks import ImageUploadTask
from apps.product.utils import prep_file_data

logger = logging.getLogger(__name__)


class ProductListView(ListView):
    model = Product
    template_name = "product-list.html"
    context_object_name = "products"
    paginate_by = settings.PAGINATION_PAGE_SIZE

    def get_queryset(self):
        queryset = super().get_queryset()
        modified = self.request.GET.get("modified", None)
        if modified is not None:
            modified = modified.lower()
            if modified == "true":
                queryset = queryset.filter(modified=True)
            elif modified == "false":
                queryset = queryset.filter(modified=False)
        return queryset


class ProductCreateView(View):
    form_class = ProductForm
    template_name = "product-create.html"
    success_url = reverse_lazy("product:product-list")

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            logo_file = form.cleaned_data.get("logo_file")
            data = prep_file_data(logo_file)

            try:
                product = form.save()
                ImageUploadTask().delay(product.uuid, data)
                return redirect(self.success_url)
            except Exception as e:
                logger.error(e)

        return render(request, self.template_name, {"form": form})


class ProductDetailView(DetailView):
    model = Product
    template_name = "product-detail.html"


class ProductUpdateView(View):
    form_class = ProductForm
    template_name = "product-update.html"
    success_url = reverse_lazy("product:product-list")

    def get(self, request, pk):
        product = get_object_or_404(Product, uuid=pk)
        form = self.form_class(instance=product)
        return render(request, self.template_name, {"form": form, "product": product})

    def post(self, request, pk):
        product = Product.objects.get(uuid=pk)
        if product.modified:
            return HttpResponse("Product has already been modified")

        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            logo_file = form.cleaned_data.get("logo_file")
            data = prep_file_data(logo_file)

            try:
                form.save()
                product.modified = True
                product.save()
                ImageUploadTask().delay(product.uuid, data)
                return redirect(self.success_url)
            except Exception as e:
                logger.error(e)

        return render(request, self.template_name, {"form": form, "product": product})


class ProductDeleteView(DeleteView):
    model = Product
    template_name = "product-delete.html"
    success_url = reverse_lazy("product:product-list")

apps/product/templates/base.html
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

    </head>
<body>
    {% block content %}
    {% endblock %}
</body>

</html>

apps/product/templates/product-create.html
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h5>Create New Product</h5>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <a type="button" class="btn btn-danger" href="{%url 'product:product-list' %}">Cancel</a>
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>
{% endblock %}

apps/product/templates/product-delete.html
{% extends "base.html" %}

{% block content %}
    <div class="card-body">
        <h4>Delete Product</h4>
        <p>Are you sure you want to delete "{{ object.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <a class="btn btn-secondary" href="{% url 'product:product-list' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

apps/product/templates/product-detail.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <br>
    <br>
    <br>
    <h4>Product Detail: {{object.name}}</h4>
    <p>Name: {{object.name}}</p>
    <p>Description: {{object.description}}</p>
    <p>Created at: {{object.created}}</p>

    {% if object.modified %}
    <p>Updated at: {{object.updated}}</p>
    <p>Is Modified: {{object.modified}}</p>
    {% endif %}

    <p>Rotate Duration: {{object.rotate_duration}}</p>


    <img src="{{ product.logo }}" alt="product.name" width="100px" height="100px">
    <div>
        <a type="button" class="btn btn-info"
           href="{% url 'product:product-list'%}">Back</a>
        <a type="button" class="btn btn-warning"
           href="{% url 'product:product-update' product.uuid %}">Update</a>
        <a type="button" class="btn btn-danger"
           href="{% url 'product:product-delete' product.uuid %}">Delete</a>
    </div>
</div>

{% endblock content %}

apps/product/templates/product-list.html
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h4>Products List</h4>
    <form method="get">
        <div class="form-group" class="form-inline mb-3">
            <label for="modified">Filter by Modified:</label>
            <select class="form-control" id="modified" name="modified">
                <option value="" {% if modified == "" %}selected{% endif %}>All Products</option>
                <option value="true" {% if modified == "true" %}selected{% endif %}>Modified Products</option>
                <option value="false" {% if modified == "false" %}selected{% endif %}>Unmodified Products</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Apply Filter</button>
    </form>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Logo</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
        <tr>
            <td><img src="{{ product.logo }}" alt="{{ product.name }}" width="60" height="60"></td>
            <td>{{ product.name }}</td>
            <td>{{ product.description }}</td>
            <td>
                <a type="button" class="btn btn-info"
                   href="{% url 'product:product-detail' product.uuid %}">View</a>
                <a type="button" class="btn btn-warning"
                   href="{% url 'product:product-update' product.uuid %}">Update</a>
                <a type="button" class="btn btn-danger"
                   href="{% url 'product:product-delete' product.uuid %}">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a type="button" class="btn btn-success" href="{%url 'product:product-create' %}">Create</a>
</div>
{% endblock %}

apps/product/templates/product-update.html
{% extends "base.html" %}
{% block content %}
<div class="card-body">
    <h4>Update Product</h4>
    <div>
        <img src="{{ product.logo }}" alt="product.name" width="100px" height="100px">
    </div>
    <!--begin::Form-->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            <input type="{{ field.field.widget.input_type }}"
                   class="form-control {{ field.css_classes }}"
                   id="{{ field.id_for_label }}"
                   name="{{ field.html_name }}"
                   value="{{ field.value|default_if_none:'' }}"
                   {% if field.field.required %}required{% endif %}>
            {% if field.help_text %}
            <small id="{{ field.id_for_label }}Help" class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
            {% if field.errors %}
            {% for error in field.errors %}
            <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
        <a type="button" class="btn btn-danger" href="{% url 'product:product-list' %}">Cancel</a>
        <button type="submit" class="btn btn-success">Update</button>
    </form>
    <!--end::Form-->
</div>
{% endblock %}